### ISSUE TITLE
문제인대통령연설문 코드 관련 문의

### ISSUE THREAD

**Issue by HAYJJAY** [bjpublic/tmwithpython#2]
안녕하세요 책보면서 열심히 따라하고 있습니다.

그 와중에 막히는 부분이 있어 문의 남깁니다.

p.70 문제인 대통령 코드를 실행해봤더니

Jpype1와 관련된 warning이 뜨면서 안돌아가서요..
Deprecated: convertStrings was not specified when starting the JVM. The default
behavior in JPype will be False starting in JPype 0.8. The recommended setting
for new code is convertStrings=False.  The legacy value of True was assumed for
this session. If you are a user of an application that reported this warning,
please file a ticket with the developer.

찾아보니 jpype1 0.7버젼을 설치해서 문제가 발생했다고 하여 0.6으로 downgrade하라는데 downgrade는 어떻게 하는지를 몰라서요..

관련해서 도움 부탁 드립니다.

**Comment by bjpublic** [comment]
안녕하세요

해당 내용 문의해본 결과

pip uninstall 명령어로 설치한 jpype 삭제하시고 다시 pip install 명령어로 버전에 맞는 jpype 설치하면 될것으로 확인 되었습니다.

감사합니다.

추가로 문의가 필요하면 언제든지 말씀해주세요
